image: ubuntu:16.04
pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get -y upgrade

          # Install downward-lab dependencies.
          - apt-get -y install mercurial python2.7 python-matplotlib python-simplejson

          # Install dependencies of this script and downward-lab tests.
          - apt-get -y install python-pip realpath wget
          - pip install -U pep8 pyflakes pytest sphinx vulture

          # Print information about environment.
          - python --version

          # Clone Fast Downward.
          - apt-get -y install mercurial g++ cmake make python g++-multilib
          - ls
          - export DOWNWARD_REPO=`realpath fast-downward`
          - hg clone http://hg.fast-downward.org ${DOWNWARD_REPO}

          # Clone benchmarks.
          - export DOWNWARD_BENCHMARKS=`realpath downward-benchmarks`
          - hg clone https://bitbucket.org/aibasel/downward-benchmarks ${DOWNWARD_BENCHMARKS}

          # Download and compile FF (used by example experiment).
          - apt-get -y install g++ make flex bison
          - wget http://fai.cs.uni-saarland.de/hoffmann/ff/FF-v2.3.tgz
          - tar -xzvf FF-v2.3.tgz
          - cd FF-v2.3/
          - make
          - cp ff ../
          - cd ..

          # Add FF to PATH.
          - export PATH="$(pwd):$PATH"

          - cd examples
          - ./lmcut.py --all
          - cat /opt/atlassian/pipelines/agent/build/examples/data/lmcut/driver.log || true
          - cat /opt/atlassian/pipelines/agent/build/examples/data/lmcut/driver.err || true
          - cat /opt/atlassian/pipelines/agent/build/examples/data/lmcut/runs-00001-00100/00001/driver.err || true
          - cat /opt/atlassian/pipelines/agent/build/examples/data/lmcut/runs-00001-00100/00001/driver.log || true
          - cat /opt/atlassian/pipelines/agent/build/examples/data/lmcut/runs-00001-00100/00001/run.log || true
          - cat /opt/atlassian/pipelines/agent/build/examples/data/lmcut/runs-00001-00100/00001/run.err || true

          #- ./tests/run-tests

          #- find .

