pipelines:
  default:
    - step:
        script:
          # Install dependencies.
          - sudo apt-get update
          - sudo apt-get -y install mercurial python2.7 python-matplotlib python-simplejson realpath
          - wget https://bootstrap.pypa.io/get-pip.py
          - sudo python get-pip.py
          - sudo python -m pip install -U pep8 pyflakes pytest sphinx
          - sudo pip install -U vulture

          # The docker container uses ASCII encoding "ANSI_X3.4-1968" by default.
          - export LANG="C.UTF-8"
          - export LC_ALL="C.UTF-8"

          # Print information about environment.
          - python --version
          - python -c "import sys; print(sys.getfilesystemencoding())"
          - python -c "import locale; print(locale.getlocale())"

          - ./tests/run-tests
